spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aid_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Cyx.chen27
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
server:
  port: 8081

# 文件上传配置
file:
  upload-dir: ${user.dir}/uploads